# Generated by Django 4.2.11 on 2024-04-08 16:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prodName', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2)])),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type', models.CharField(choices=[('raw', 'raw'), ('dish', 'dish')], max_length=4)),
            ],
        ),
    ]
