# Generated by Django 4.2.11 on 2024-04-08 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('raw', 'Raw Material'), ('dish', 'Dish')], max_length=4),
        ),
    ]
