# Generated by Django 4.2.11 on 2024-04-08 17:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prodName',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
    ]
